/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.awt.Image;
import java.io.File;
import java.util.regex.*;   
import javax.swing.ImageIcon; 
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.profile;

/**
 *
 * @author mehta
 */
public class CreateJPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form CreateJPanel
     */
   // ImageIcon imagegirl = newImageIcon("girl.jpg");
    String filename;
    

    profile profile;
    public CreateJPanel(profile profile) {
        initComponents();
        this.profile = profile;  
        
         
        
    }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbgeographic = new javax.swing.JLabel();
        lbdob = new javax.swing.JLabel();
        lbtelephone = new javax.swing.JLabel();
        lbfax = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbssn = new javax.swing.JLabel();
        lbmedicalrecordnumber = new javax.swing.JLabel();
        lbhealthplannumber = new javax.swing.JLabel();
        lbbankaccount = new javax.swing.JLabel();
        lblicensenumber = new javax.swing.JLabel();
        lbvehiclenumber = new javax.swing.JLabel();
        lbdevicenumber = new javax.swing.JLabel();
        lblinkedin = new javax.swing.JLabel();
        lbip = new javax.swing.JLabel();
        lbuniqueidentifyingnumber = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtgeographicdata = new javax.swing.JTextField();
        txttelephonenumber = new javax.swing.JTextField();
        txtfaxnumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsocialnumber = new javax.swing.JTextField();
        txtmedicalnumber = new javax.swing.JTextField();
        txthealthnumber = new javax.swing.JTextField();
        txtbankaccountnumber = new javax.swing.JTextField();
        txtlicensenumber = new javax.swing.JTextField();
        txtvehiclenumber = new javax.swing.JTextField();
        txtdeviceidentifiers = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txtinternetprotocol = new javax.swing.JTextField();
        txtuniqueidentifier = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        flbname = new javax.swing.JLabel();
        flbgeographicdata = new javax.swing.JLabel();
        flbtelephonenumber = new javax.swing.JLabel();
        flbsocialsecuritynumber = new javax.swing.JLabel();
        flbfaxnumber = new javax.swing.JLabel();
        flbmedicalrecordnumber = new javax.swing.JLabel();
        flbemailaddress = new javax.swing.JLabel();
        flbhealthplanbeneficiarynumber = new javax.swing.JLabel();
        flbbankaccountnumbers = new javax.swing.JLabel();
        flbuniqueidentifyingnumber = new javax.swing.JLabel();
        flblicensenumber = new javax.swing.JLabel();
        flblinkedin = new javax.swing.JLabel();
        flbinternetprotocoladdresses = new javax.swing.JLabel();
        flbvehiclenumber = new javax.swing.JLabel();
        flbdevicenumber = new javax.swing.JLabel();
        lbfacephoto = new javax.swing.JLabel();
        txtphoto = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Personal Profile");

        lbname.setText("Name");

        lbgeographic.setText("Geographic data");

        lbdob.setText("Date of Birth");

        lbtelephone.setText("Telephone number");

        lbfax.setText("Fax number");

        lbemail.setText("Email address");

        lbssn.setText("Social Security number");

        lbmedicalrecordnumber.setText("Medical record number");

        lbhealthplannumber.setText("Health plan beneficiary number");

        lbbankaccount.setText("Bank account numbers");

        lblicensenumber.setText("license number");

        lbvehiclenumber.setText("Vehicle identifiers and serial numbers including license plate");

        lbdevicenumber.setText("Device identifiers and serial numbers");

        lblinkedin.setText("LinkedIn");

        lbip.setText("Internet protocol addresses");

        lbuniqueidentifyingnumber.setText("unique identifying number");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        txtgeographicdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeographicdataActionPerformed(evt);
            }
        });
        txtgeographicdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgeographicdataKeyReleased(evt);
            }
        });

        txttelephonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelephonenumberKeyReleased(evt);
            }
        });

        txtfaxnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfaxnumberKeyReleased(evt);
            }
        });

        txtsocialnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsocialnumberKeyReleased(evt);
            }
        });

        txtmedicalnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmedicalnumberKeyReleased(evt);
            }
        });

        txthealthnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthealthnumberKeyReleased(evt);
            }
        });

        txtbankaccountnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbankaccountnumberKeyReleased(evt);
            }
        });

        txtlicensenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlicensenumberKeyReleased(evt);
            }
        });

        txtvehiclenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvehiclenumberKeyReleased(evt);
            }
        });

        txtdeviceidentifiers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdeviceidentifiersKeyReleased(evt);
            }
        });

        txtlinkedin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlinkedinKeyReleased(evt);
            }
        });

        txtinternetprotocol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinternetprotocolKeyReleased(evt);
            }
        });

        txtuniqueidentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniqueidentifierActionPerformed(evt);
            }
        });
        txtuniqueidentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuniqueidentifierKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        flbname.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbname.setForeground(new java.awt.Color(255, 51, 51));

        flbgeographicdata.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbgeographicdata.setForeground(new java.awt.Color(255, 51, 51));

        flbtelephonenumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbtelephonenumber.setForeground(new java.awt.Color(255, 51, 51));

        flbsocialsecuritynumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbsocialsecuritynumber.setForeground(new java.awt.Color(255, 51, 51));

        flbfaxnumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbfaxnumber.setForeground(new java.awt.Color(255, 51, 51));

        flbmedicalrecordnumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbmedicalrecordnumber.setForeground(new java.awt.Color(255, 51, 51));

        flbemailaddress.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbemailaddress.setForeground(new java.awt.Color(255, 51, 51));
        flbemailaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                flbemailaddressKeyReleased(evt);
            }
        });

        flbhealthplanbeneficiarynumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbhealthplanbeneficiarynumber.setForeground(new java.awt.Color(255, 51, 51));

        flbbankaccountnumbers.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbbankaccountnumbers.setForeground(new java.awt.Color(255, 51, 51));

        flbuniqueidentifyingnumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbuniqueidentifyingnumber.setForeground(new java.awt.Color(255, 51, 51));

        flblicensenumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flblicensenumber.setForeground(new java.awt.Color(255, 51, 51));

        flblinkedin.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flblinkedin.setForeground(new java.awt.Color(255, 51, 51));

        flbinternetprotocoladdresses.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbinternetprotocoladdresses.setForeground(new java.awt.Color(255, 51, 51));

        flbvehiclenumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbvehiclenumber.setForeground(new java.awt.Color(255, 51, 51));

        flbdevicenumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        flbdevicenumber.setForeground(new java.awt.Color(255, 51, 51));

        lbfacephoto.setText("Face photo & Biometerics identifiers");

        txtphoto.setText("Browser");
        txtphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphotoActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbemail)
                            .addComponent(lbssn)
                            .addComponent(lbmedicalrecordnumber)
                            .addComponent(lbhealthplannumber)
                            .addComponent(lbbankaccount)
                            .addComponent(lblicensenumber)
                            .addComponent(lbvehiclenumber)
                            .addComponent(lbdevicenumber)
                            .addComponent(lblinkedin)
                            .addComponent(lbip)
                            .addComponent(lbuniqueidentifyingnumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbgeographic)
                            .addComponent(lbname)
                            .addComponent(lbdob)
                            .addComponent(lbtelephone)
                            .addComponent(lbfax))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flbmedicalrecordnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flbhealthplanbeneficiarynumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flbbankaccountnumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flblinkedin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flbemailaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(39, 39, 39))
                            .addComponent(flblicensenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flbvehiclenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flbdevicenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flbsocialsecuritynumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(flbtelephonenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flbuniqueidentifyingnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flbinternetprotocoladdresses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flbname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flbgeographicdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(flbfaxnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtgeographicdata)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmedicalnumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtuniqueidentifier)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttelephonenumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtvehiclenumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtinternetprotocol)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfaxnumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txthealthnumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtname)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtlicensenumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtemail)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtlinkedin)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtsocialnumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbankaccountnumber)
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtdeviceidentifiers)
                        .addGap(195, 195, 195))))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbfacephoto)
                        .addGap(103, 103, 103)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtphoto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbname)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(flbname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbgeographic)
                        .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(flbgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdob)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtelephone)
                            .addComponent(txttelephonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(flbtelephonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbfax)
                        .addComponent(txtfaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(flbfaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(flbsocialsecuritynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbemail)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(flbemailaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lbssn)
                                                    .addComponent(txtsocialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lbmedicalrecordnumber)
                                                    .addComponent(txtmedicalnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(flbmedicalrecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbhealthplannumber)
                                            .addComponent(txthealthnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(flbhealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbbankaccount)
                                    .addComponent(txtbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(flbbankaccountnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblicensenumber)
                                .addComponent(txtlicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(flblicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbvehiclenumber)
                                .addComponent(txtvehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(flbvehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(flbdevicenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbdevicenumber)
                                .addComponent(txtdeviceidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblinkedin)
                                .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(flblinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtinternetprotocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuniqueidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbuniqueidentifyingnumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbfacephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphoto)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnSave)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flbinternetprotocoladdresses, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(flbuniqueidentifyingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtuniqueidentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniqueidentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniqueidentifierActionPerformed

    private void txtgeographicdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeographicdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeographicdataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        profile.setName(txtname.getText());
        profile.setGeographicdata(txtgeographicdata.getText());
        profile.setDOB(jDateChooser1.getDate());
        profile.setTelephonenumber(txttelephonenumber.getText());
        profile.setFaxnumber(txtfaxnumber.getText());
        profile.setEmailaddress(txtemail.getText());
        profile.setSocialsecuritynumber(txtsocialnumber.getText());
        profile.setMedicalrecordnumber(Integer.parseInt(txtmedicalnumber.getText()));
        profile.setHealthnumber(Integer.parseInt(txthealthnumber.getText()));
        profile.setBankaccountnumber(Integer.parseInt(txtbankaccountnumber.getText()));
        profile.setCertificatenumber(txtlicensenumber.getText());
        profile.setVehiclenumber(txtvehiclenumber.getText());
        profile.setSerialnumber(Integer.parseInt(txtdeviceidentifiers.getText()));
        profile.setLinkedin(txtlinkedin.getText());
        profile.setInternetaddress(txtinternetprotocol.getText());
        profile.setUniquenumber(Integer.parseInt(txtuniqueidentifier.getText())); 
       profile.setPath(jTextField1.getText());  
       profile.setPhoto(filename);
       
        
        JOptionPane.showMessageDialog(this, "Successfully Saved");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{3,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtname.getText());
        if(!match.matches()){
        flbname.setText("Naming convention is invalid, please use lower case or upper case alphabets and lenght between 3 to 20 ");
        }
        else {
        flbname.setText(null);
        }  
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtgeographicdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgeographicdataKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9/,]{0,50}[][a-zA-Z0-9]{0,50}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtgeographicdata.getText());
        if(!match.matches()){
        flbgeographicdata.setText("Cannot be empty");
        }
        else {
        flbgeographicdata.setText(null);
        }  
    }//GEN-LAST:event_txtgeographicdataKeyReleased

    private void flbemailaddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_flbemailaddressKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]\n" +
"        Matcher match=patt.matcher(txtemail.getText());{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtemail.getText());
        if(!match.matches()){
        flbemailaddress.setText("Please enter email id in proper format name@xyz.com");
        }
        else {
        flbemailaddress.setText(null);
        } 
    }//GEN-LAST:event_flbemailaddressKeyReleased

    private void txttelephonenumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelephonenumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txttelephonenumber.getText());
        if(!match.matches()){
        flbtelephonenumber.setText("Telephone number is invalid ");
        }
        else {
        flbtelephonenumber.setText(null);
        }  
    }//GEN-LAST:event_txttelephonenumberKeyReleased

    private void txtfaxnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxnumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtfaxnumber.getText());
        if(!match.matches()){
        flbfaxnumber.setText("fax number is invalid ");
        }
        else {
        flbfaxnumber.setText(null);
        }  
    }//GEN-LAST:event_txtfaxnumberKeyReleased

    private void txtsocialnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsocialnumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtsocialnumber.getText());
        if(!match.matches()){
        flbsocialsecuritynumber.setText("social number is invalid ");
        }
        else {
        flbsocialsecuritynumber.setText(null);
        }  
    }//GEN-LAST:event_txtsocialnumberKeyReleased

    private void txtmedicalnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedicalnumberKeyReleased
        // TODO add your handling code here:
         String PATTERN="^[a-zA-Z0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtmedicalnumber.getText());
        if(!match.matches()){
        flbmedicalrecordnumber.setText("medical number is invalid ");
        }
        else {
        flbmedicalrecordnumber.setText(null);
        } 
    }//GEN-LAST:event_txtmedicalnumberKeyReleased

    private void txthealthnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthealthnumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txthealthnumber.getText());
        if(!match.matches()){
        flbhealthplanbeneficiarynumber.setText("health number is invalid ");
        }
        else {
        flbhealthplanbeneficiarynumber.setText(null);
        } 
    }//GEN-LAST:event_txthealthnumberKeyReleased

    private void txtbankaccountnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbankaccountnumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtbankaccountnumber.getText());
        if(!match.matches()){
        flbbankaccountnumbers.setText("bank account is invalid ");
        }
        else {
        flbbankaccountnumbers.setText(null);
        } 
    }//GEN-LAST:event_txtbankaccountnumberKeyReleased

    private void txtlicensenumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicensenumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,15}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtlicensenumber.getText());
        if(!match.matches()){
        flblicensenumber.setText("license number is invalid ");
        }
        else {
        flblicensenumber.setText(null);
        } 
    }//GEN-LAST:event_txtlicensenumberKeyReleased

    private void txtvehiclenumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehiclenumberKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtvehiclenumber.getText());
        if(!match.matches()){
        flbvehiclenumber.setText("vehicle number is invalid ");
        }
        else {
        flbvehiclenumber.setText(null);
        } 
    }//GEN-LAST:event_txtvehiclenumberKeyReleased

    private void txtdeviceidentifiersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeviceidentifiersKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtdeviceidentifiers.getText());
        if(!match.matches()){
        flbdevicenumber.setText("device identifier number is invalid ");
        }
        else {
        flbdevicenumber.setText(null);
        } 
    }//GEN-LAST:event_txtdeviceidentifiersKeyReleased

    private void txtlinkedinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlinkedinKeyReleased
        // TODO add your handling code here:
        //linkedin.com/in/firsname-lastname-numbers/
        
    }//GEN-LAST:event_txtlinkedinKeyReleased

    private void txtinternetprotocolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinternetprotocolKeyReleased
        // TODO add your handling code here:
        //192.158.1.39
        String PATTERN="^[0-9]{0,3}[.][0-9]{0,3}[.][0-9]{0,2}[.][0-9]{0,3}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtinternetprotocol.getText());
        if(!match.matches()){
        flbinternetprotocoladdresses.setText("internet protocol number is invalid ");
        }
        else {
        flbinternetprotocoladdresses.setText(null);
        } 
    }//GEN-LAST:event_txtinternetprotocolKeyReleased

    private void txtuniqueidentifierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuniqueidentifierKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,12}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(txtuniqueidentifier.getText());
        if(!match.matches()){
        flbuniqueidentifyingnumber.setText("unique identifier number is invalid ");
        }
        else {
        flbuniqueidentifyingnumber.setText(null);
        } 
    }//GEN-LAST:event_txtuniqueidentifierKeyReleased

    private void txtphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphotoActionPerformed
JFileChooser chooser = new JFileChooser();
chooser.showOpenDialog(null);
File f= chooser.getSelectedFile();
 filename= f.getAbsolutePath();
jTextField1.setText(filename);
Image getAbsolutePath = null;
ImageIcon photo= new ImageIcon(filename);
//Image image = photo.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
//jLabel1.setIcon(photo);
    }//GEN-LAST:event_txtphotoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

 
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel flbbankaccountnumbers;
    private javax.swing.JLabel flbdevicenumber;
    private javax.swing.JLabel flbemailaddress;
    private javax.swing.JLabel flbfaxnumber;
    private javax.swing.JLabel flbgeographicdata;
    private javax.swing.JLabel flbhealthplanbeneficiarynumber;
    private javax.swing.JLabel flbinternetprotocoladdresses;
    private javax.swing.JLabel flblicensenumber;
    private javax.swing.JLabel flblinkedin;
    private javax.swing.JLabel flbmedicalrecordnumber;
    private javax.swing.JLabel flbname;
    private javax.swing.JLabel flbsocialsecuritynumber;
    private javax.swing.JLabel flbtelephonenumber;
    private javax.swing.JLabel flbuniqueidentifyingnumber;
    private javax.swing.JLabel flbvehiclenumber;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbbankaccount;
    private javax.swing.JLabel lbdevicenumber;
    private javax.swing.JLabel lbdob;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbfacephoto;
    private javax.swing.JLabel lbfax;
    private javax.swing.JLabel lbgeographic;
    private javax.swing.JLabel lbhealthplannumber;
    private javax.swing.JLabel lbip;
    private javax.swing.JLabel lblicensenumber;
    private javax.swing.JLabel lblinkedin;
    private javax.swing.JLabel lbmedicalrecordnumber;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbssn;
    private javax.swing.JLabel lbtelephone;
    private javax.swing.JLabel lbuniqueidentifyingnumber;
    private javax.swing.JLabel lbvehiclenumber;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtbankaccountnumber;
    private javax.swing.JTextField txtdeviceidentifiers;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfaxnumber;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txthealthnumber;
    private javax.swing.JTextField txtinternetprotocol;
    private javax.swing.JTextField txtlicensenumber;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmedicalnumber;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton txtphoto;
    private javax.swing.JTextField txtsocialnumber;
    private javax.swing.JTextField txttelephonenumber;
    private javax.swing.JTextField txtuniqueidentifier;
    private javax.swing.JTextField txtvehiclenumber;
    // End of variables declaration//GEN-END:variables

   //rivate ImageIcon newImageIcon(String girljpg) {
    //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    //private LocalDate LocalDate(String text) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
