/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import model.profile;

/**
 *
 * @author mehta
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    profile profile; 
    //private Date D;
    public ViewJPanel(profile profile) {
        initComponents();
        this.profile = profile; 
        ViewJPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbgeographic = new javax.swing.JLabel();
        lbdob = new javax.swing.JLabel();
        lbtelephone = new javax.swing.JLabel();
        lbfax = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lbssn = new javax.swing.JLabel();
        lbmedicalrecordnumber = new javax.swing.JLabel();
        lbhealthplannumber = new javax.swing.JLabel();
        lbbankaccount = new javax.swing.JLabel();
        lblicensenumber = new javax.swing.JLabel();
        lbvehiclenumber = new javax.swing.JLabel();
        lbdevicenumber = new javax.swing.JLabel();
        lblinkedin = new javax.swing.JLabel();
        lbip = new javax.swing.JLabel();
        lbuniqueidentifyingnumber = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtgeographicdata = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txttelephonenumber = new javax.swing.JTextField();
        txtfaxnumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsocialnumber = new javax.swing.JTextField();
        txtmedicalnumber = new javax.swing.JTextField();
        txthealthnumber = new javax.swing.JTextField();
        txtbankaccountnumber = new javax.swing.JTextField();
        txtlicensenumber = new javax.swing.JTextField();
        txtvehiclenumber = new javax.swing.JTextField();
        txtdeviceidentifiers = new javax.swing.JTextField();
        txtlinkedin = new javax.swing.JTextField();
        txtinternetprotocol = new javax.swing.JTextField();
        txtuniqueidentifier = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        lbface = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Personal Profile");

        lbname.setText("Name");

        lbgeographic.setText("Geographic data");

        lbdob.setText("Date of Birth");

        lbtelephone.setText("Telephone number");

        lbfax.setText("Fax number");

        lbemail.setText("Email address");

        lbssn.setText("Social Security number");

        lbmedicalrecordnumber.setText("Medical record number");

        lbhealthplannumber.setText("Health plan beneficiary number");

        lbbankaccount.setText("Bank account numbers");

        lblicensenumber.setText("license number");

        lbvehiclenumber.setText("Vehicle identifiers and serial numbers including license plate");

        lbdevicenumber.setText("Device identifiers and serial numbers");

        lblinkedin.setText("LinkedIn");

        lbip.setText("Internet protocol addresses");

        lbuniqueidentifyingnumber.setText("unique identifying number");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtgeographicdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgeographicdataActionPerformed(evt);
            }
        });

        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });

        txtuniqueidentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniqueidentifierActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Face");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbgeographic)
                            .addComponent(lbname)
                            .addComponent(lbdob)
                            .addComponent(lbtelephone)
                            .addComponent(lbfax)
                            .addComponent(lbemail)
                            .addComponent(lbssn)
                            .addComponent(lbmedicalrecordnumber)
                            .addComponent(lbhealthplannumber)
                            .addComponent(lbbankaccount)
                            .addComponent(lblicensenumber)
                            .addComponent(lbvehiclenumber)
                            .addComponent(lbdevicenumber)
                            .addComponent(lblinkedin)
                            .addComponent(lbip)
                            .addComponent(lbuniqueidentifyingnumber)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname)
                            .addComponent(txtgeographicdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtdob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txttelephonenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtsocialnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtmedicalnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txthealthnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtbankaccountnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtlicensenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtvehiclenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtdeviceidentifiers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtlinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtinternetprotocol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtuniqueidentifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(txtfaxnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbface)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbgeographic)
                    .addComponent(txtgeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbdob)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtelephone)
                    .addComponent(txttelephonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfax)
                    .addComponent(txtfaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbssn)
                    .addComponent(txtsocialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmedicalrecordnumber)
                    .addComponent(txtmedicalnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbhealthplannumber)
                    .addComponent(txthealthnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbankaccount)
                    .addComponent(txtbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblicensenumber)
                    .addComponent(txtlicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbvehiclenumber)
                    .addComponent(txtvehiclenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdevicenumber)
                    .addComponent(txtdeviceidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinkedin)
                    .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbip)
                    .addComponent(txtinternetprotocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbuniqueidentifyingnumber)
                    .addComponent(txtuniqueidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbface)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtgeographicdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeographicdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeographicdataActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    private void txtuniqueidentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniqueidentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniqueidentifierActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbbankaccount;
    private javax.swing.JLabel lbdevicenumber;
    private javax.swing.JLabel lbdob;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbface;
    private javax.swing.JLabel lbfax;
    private javax.swing.JLabel lbgeographic;
    private javax.swing.JLabel lbhealthplannumber;
    private javax.swing.JLabel lbip;
    private javax.swing.JLabel lblicensenumber;
    private javax.swing.JLabel lblinkedin;
    private javax.swing.JLabel lbmedicalrecordnumber;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbssn;
    private javax.swing.JLabel lbtelephone;
    private javax.swing.JLabel lbuniqueidentifyingnumber;
    private javax.swing.JLabel lbvehiclenumber;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtbankaccountnumber;
    private javax.swing.JTextField txtdeviceidentifiers;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfaxnumber;
    private javax.swing.JTextField txtgeographicdata;
    private javax.swing.JTextField txthealthnumber;
    private javax.swing.JTextField txtinternetprotocol;
    private javax.swing.JTextField txtlicensenumber;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmedicalnumber;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsocialnumber;
    private javax.swing.JTextField txttelephonenumber;
    private javax.swing.JTextField txtuniqueidentifier;
    private javax.swing.JTextField txtvehiclenumber;
    // End of variables declaration//GEN-END:variables

    private void ViewJPanel() {
        
            
        txtname.setText(profile.getName()); //To change body of generated methods, choose Tools | Templates.
        txtgeographicdata.setText(profile.getGeographicdata());
        SimpleDateFormat dateformat = new SimpleDateFormat("dd-MM-yyyy");
        String thedate = dateformat.format(profile.getDOB());
       txtdob.setText(thedate);
       txttelephonenumber.setText(profile.getTelephonenumber());
       txtfaxnumber.setText(profile.getFaxnumber());
       txtemail.setText(profile.getEmailaddress());
       txtsocialnumber.setText(profile.getSocialsecuritynumber());
       String medical = Integer.toString(profile.getMedicalrecordnumber());
         txtmedicalnumber.setText(medical);
       String health = Integer.toString(profile.getHealthnumber());
         txthealthnumber.setText(health);
       String bank = Integer.toString(profile.getBankaccountnumber());
         txtbankaccountnumber.setText(bank);
       txtlicensenumber.setText(profile.getCertificatenumber());
       txtvehiclenumber.setText(profile.getVehiclenumber());
       String device = Integer.toString(profile.getSerialnumber());
       txtdeviceidentifiers.setText(device);
       txtlinkedin.setText(profile.getLinkedin());
       txtinternetprotocol.setText(profile.getInternetaddress());
       String unique = Integer.toString(profile.getUniquenumber());
       txtuniqueidentifier.setText(unique);
       lbface.setIcon(new ImageIcon(new ImageIcon(profile.getPhoto()).getImage().getScaledInstance(200,200,Image.SCALE_DEFAULT)));
     
       jTextField1.setText(profile.getPath());     
       
       
    }
}
